### ISSUE TITLE
I can not run composer update

### ISSUE THREAD

**Issue by vnscorpion** [powerkernel/directadmin-s3-backup#1]
Hi, i can not run composer update, please know me how to run it. I use Directadmin 1.58.2
Thanks!

**Comment by harrytang** [comment]
cannot reproduce!

**Comment by felinto-dev** [comment]
> Hi, i can not run composer update, please know me how to run it. I use Directadmin 1.58.2 Thanks!

DON'T execute this line: 

`php -r "if (hash_file('sha384', 'composer-setup.php') === 'c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"`

No idea what the author was thinking when wrote this.
